# Generated by Django 3.1.3 on 2020-11-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='like',
            new_name='good',
        ),
    ]
